#!/usr/bin/env bash
# ==========================================================
# 🧠 IGB ERP Smart Heavy Cleaner v5.4-pro
# 作者: IGB Tung (generated)
# 功能:
#   - 偵測並搬移 >100MB 大檔至 ~/.cache/igb-heavy/
#   - 建立專案壓縮備份並保留最近 N 個備份
#   - 更新 .gitignore (安全排除清單)
#   - Git 安全提交與推送 (含權限/連線檢查)
#   - Telegram 成功/失敗通知 (若已設定環境變數)
#   - 產生命令與結果日誌
# ==========================================================

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

DATE="$(date '+%Y-%m-%d_%H-%M-%S')"
LOG_DIR="$PROJECT_ROOT/tools/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/smart-heavy-cleaner-v5.4-pro-$DATE.log"

HEAVY_CACHE="$HOME/.cache/igb-heavy"
mkdir -p "$HEAVY_CACHE"
BACKUP_DIR="$PROJECT_ROOT/tools/backups"
mkdir -p "$BACKUP_DIR"
KEEP_BACKUPS=5

# telegram env (optional)
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN-}"
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID-}"
TELEGRAM_ENABLED=0
if [[ -n "$TELEGRAM_BOT_TOKEN" && -n "$TELEGRAM_CHAT_ID" ]]; then
  TELEGRAM_ENABLED=1
fi

# helper: log
log(){
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

# start
log "🚀 Smart Heavy Cleaner v5.4-pro 啟動"

# Step 1: find and move files >100M (exclude .git, tools/backups, yes, node_modules)
log "🔎 偵測 >100MB 檔案..."
MOVED_COUNT=0
find . -type f -size +100M -not -path './.git/*' -not -path './yes/*' -not -path './tools/backups/*' -not -path './tools/reports/*' -not -path './node_modules/*' 2>/dev/null | while read -r FILE; do
  # normalize
  FILE="${FILE#./}"
  TARGET_DIR="$HEAVY_CACHE/$(dirname "$FILE")"
  mkdir -p "$TARGET_DIR"
  BASENAME="$(basename "$FILE")"
  log "⚙ 偵測到大檔案: $FILE"
  if mv -- "$FILE" "$TARGET_DIR/" 2>/dev/null; then
    # create stub file to indicate removal
    printf "[MOVED to %s on %s]\n" "$TARGET_DIR/$BASENAME" "$(date '+%Y-%m-%d %H:%M:%S')" > "$FILE"
    log "✅ 已搬移：$FILE -> $TARGET_DIR/$BASENAME"
    ((MOVED_COUNT++))
  else
    log "⚠ 無法搬移: $FILE"
  fi
done
log "📦 大檔案搬移完成 (共搬移: $MOVED_COUNT)"

# Step 2: update .gitignore safely (append only missing entries)
log "🧾 更新 .gitignore（append 缺失項目）..."
GITIGNORE_FILE="$PROJECT_ROOT/.gitignore"
mkdir -p "$(dirname "$GITIGNORE_FILE")"
cat > "$GITIGNORE_FILE.tmp" <<'EOF'
# IGB ERP autogenerated ignores
/data/
/yes/
/pgdata/
/postgres/
/caddy/data/
/caddy/config/
/tools/reports/
/tools/backups/
/logs/
/backup/
/node_modules/
__pycache__/
*.pyc
.venv/
venv/
.env
dist/
build/
*.tar.gz
EOF

# merge: keep existing lines and add missing
if [[ -f "$GITIGNORE_FILE" ]]; then
  # preserve existing and add new if missing
  awk 'FNR==NR{a[$0]=1;next} !($0 in a){print $0}' "$GITIGNORE_FILE" "$GITIGNORE_FILE.tmp" > "$GITIGNORE_FILE.merged"
  mv "$GITIGNORE_FILE.merged" "$GITIGNORE_FILE"
else
  mv "$GITIGNORE_FILE.tmp" "$GITIGNORE_FILE"
fi
rm -f "$GITIGNORE_FILE.tmp"
log "✅ .gitignore 已更新"

# Step 3: create compressed backup excluding heavy and venv and git
BACKUP_NAME="igb-design-center-$DATE.tar.gz"
BACKUP_PATH="$BACKUP_DIR/$BACKUP_NAME"
log "📦 建立專案備份: $BACKUP_NAME (會排除 .git, yes, tools/backups)"
	tar --exclude='./.git' --exclude='./yes' --exclude='./tools/backups' --exclude='./tools/reports' --exclude='./backup' -czf "$BACKUP_PATH" . 2>>"$LOG_FILE" || true
if [[ -f "$BACKUP_PATH" ]]; then
  log "✅ 備份完成: $BACKUP_PATH"
else
  log "⚠ 備份檔案未建立：$BACKUP_PATH"
fi

# retention: keep last N backups
log "🗑 保留最近 $KEEP_BACKUPS 個備份，其餘刪除"
(ls -1t "$BACKUP_DIR"/*.tar.gz 2>/dev/null || true) | tail -n +$((KEEP_BACKUPS+1)) | while read -r OLD; do
  if [[ -n "$OLD" ]]; then
    rm -f -- "$OLD" && log "🗑 刪除舊備份: $OLD"
  fi
done

# Step 4: git add/commit/push safely
log "🔄 準備 Git commit + push..."
# check inside a git repo
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  # show status
  git status --porcelain | tee -a "$LOG_FILE"
  # stage changes (exclude heavy cache and venv)
  git add -A
  # commit if there are changes
  if git diff --cached --quiet; then
    log "ℹ 無新變更可提交"
    COMMIT_DONE=0
  else
    if git commit -m "🧹 Auto-clean + backup @ $DATE" >/dev/null 2>&1; then
      log "✅ 已 commit 本次變更"
      COMMIT_DONE=1
    else
      log "⚠ commit 失敗，檢查 Git 設定與權限"
      COMMIT_DONE=0
    fi
  fi
  # push if committed
  if [[ "$COMMIT_DONE" -eq 1 ]]; then
    # check remote access
    REMOTE_URL=$(git config --get remote.origin.url || true)
    if [[ -z "$REMOTE_URL" ]]; then
      log "⚠ 未設定 remote.origin.url，跳過 push"
      PUSH_OK=0
    else
      if git ls-remote "$REMOTE_URL" >/dev/null 2>&1; then
        if git push origin main >/dev/null 2>&1; then
          log "✅ Git push 成功"
          PUSH_OK=1
        else
          log "⚠ Git push 失敗 (推送錯誤)，請手動檢查"
          PUSH_OK=0
        fi
      else
        log "⚠ 無法存取遠端倉庫 ($REMOTE_URL)；請檢查網路或權限"
        PUSH_OK=0
      fi
    fi
  else
    PUSH_OK=0
  fi
else
  log "❌ 目前不在 Git 工作目錄，無法執行 Git 操作"
  PUSH_OK=0
fi

# Step 5: Telegram notification (summary)
SUMMARY="IGB Smart Heavy Cleaner 結果:\nMoved:$MOVED_COUNT backups:$(ls -1 "$BACKUP_DIR"/*.tar.gz 2>/dev/null | wc -l) commit:$COMMIT_DONE push:$PUSH_OK"
log "📣 發送 Telegram 通知 (若啟用)"
if [[ "$TELEGRAM_ENABLED" -eq 1 ]]; then
  # send message and include the last backup as document if push ok
  curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" -d chat_id="${TELEGRAM_CHAT_ID}" -d text="$SUMMARY" >/dev/null || true
  if [[ -f "$BACKUP_PATH" ]]; then
    curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" -F chat_id="${TELEGRAM_CHAT_ID}" -F document=@"${BACKUP_PATH}" >/dev/null || true
  fi
  log "✅ Telegram 通知已發送"
else
  log "⚠ Telegram 未啟用，跳過通知"
fi

log "✅ Smart Heavy Cleaner v5.4-pro 完成"

# EOF
